#!/bin/bash
# deep-scan.sh — Phase 1 Deep Reconnaissance Scanner
# ใช้ร่วมกับ env-check.sh (source ก่อนเรียกใช้)
# Output: structured scan report สำหรับ Phase 2 Discovery Report
#
# Usage:
#   source scripts/env-check.sh && bash scripts/deep-scan.sh [project_path]
#   หรือ bash scripts/deep-scan.sh (ใช้ current dir)

PROJECT_PATH="${1:-.}"
cd "$PROJECT_PATH" || exit 1

# ใช้ tool ที่ดีที่สุดที่มี (set จาก env-check.sh หรือ detect เอง)
RG="${GOD_ARCH_RG_CMD:-$(command -v rg || echo "grep -r")}"
HAS_JQ="${GOD_ARCH_HAS_JQ:-$(command -v jq &>/dev/null && echo 1 || echo 0)}"
HAS_GIT="${GOD_ARCH_HAS_GIT:-$(command -v git &>/dev/null && echo 1 || echo 0)}"
TREE_AVAILABLE=$(command -v tree &>/dev/null && echo 1 || echo 0)

# Output file
REPORT_FILE="god-arch-scan-report.md"

echo "🔭 Starting Deep Scan → $REPORT_FILE"
echo ""

cat > "$REPORT_FILE" << 'HEADER'
# 🔍 God-Architecture Deep Scan Report

> Auto-generated by `scripts/deep-scan.sh`
> ใช้รายงานนี้ประกอบการเขียน Phase 2 Discovery Report

HEADER

echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 1: Project Structure
# ───────────────────────────────────────────
echo "▶ [1/6] Scanning project structure..."
cat >> "$REPORT_FILE" << 'EOF'
## 1. โครงสร้างโปรเจกต์

```
EOF

if [ "$TREE_AVAILABLE" = "1" ]; then
    tree -L 3 -I 'node_modules|.git|.next|.nuxt|dist|build|__pycache__|.cache|coverage' >> "$REPORT_FILE" 2>/dev/null
else
    find . -maxdepth 3 \
        -not -path '*/node_modules/*' \
        -not -path '*/.git/*' \
        -not -path '*/.next/*' \
        -not -path '*/dist/*' \
        -not -path '*/build/*' \
        -not -path '*/__pycache__/*' \
        | sort >> "$REPORT_FILE"
fi

echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 2: Tech Stack Detection
# ───────────────────────────────────────────
echo "▶ [2/6] Detecting tech stack..."
cat >> "$REPORT_FILE" << 'EOF'
## 2. Tech Stack (จากไฟล์ config จริง)

EOF

# package.json
if [ -f "package.json" ]; then
    echo "### package.json — dependencies" >> "$REPORT_FILE"
    echo '```json' >> "$REPORT_FILE"
    if [ "$HAS_JQ" = "1" ]; then
        jq '{dependencies, devDependencies} | to_entries[] | .value | to_entries[] | select(.value | test("^[\\^~]?[0-9]")) | "\(.key): \(.value)"' package.json 2>/dev/null \
            | tr -d '"' | head -30 >> "$REPORT_FILE"
    else
        python3 -c "
import json, sys
with open('package.json') as f:
    p = json.load(f)
for section in ['dependencies','devDependencies']:
    for k,v in (p.get(section,{}).items()):
        print(f'{k}: {v}')
" 2>/dev/null | head -30 >> "$REPORT_FILE"
    fi
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# pyproject.toml / requirements.txt
if [ -f "pyproject.toml" ]; then
    echo "### pyproject.toml" >> "$REPORT_FILE"
    echo '```toml' >> "$REPORT_FILE"
    grep -A 20 "\[project\]\|\[tool.poetry.dependencies\]\|\[dependencies\]" pyproject.toml 2>/dev/null | head -25 >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

if [ -f "requirements.txt" ]; then
    echo "### requirements.txt" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    cat requirements.txt | head -20 >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# Cargo.toml
if [ -f "Cargo.toml" ]; then
    echo "### Cargo.toml" >> "$REPORT_FILE"
    echo '```toml' >> "$REPORT_FILE"
    grep -A 30 "\[dependencies\]" Cargo.toml 2>/dev/null | head -30 >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# ───────────────────────────────────────────
# SECTION 3: Convention Mining
# ───────────────────────────────────────────
echo "▶ [3/6] Mining existing patterns..."
cat >> "$REPORT_FILE" << 'EOF'
## 3. Patterns ที่ใช้อยู่ปัจจุบัน

EOF

SRC_DIRS=$(find . -maxdepth 2 -type d -name "src" -o -type d -name "app" -o -type d -name "lib" 2>/dev/null | grep -v node_modules | head -5 | tr '\n' ' ')
[ -z "$SRC_DIRS" ] && SRC_DIRS="."

# Component patterns
echo "### Component Export Pattern" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if command -v rg &>/dev/null; then
    rg "^export default (function|class|const)" $SRC_DIRS --type ts --type tsx -l 2>/dev/null | head -10 >> "$REPORT_FILE" || true
    rg "^export (default |)function " $SRC_DIRS --type ts --type tsx -l 2>/dev/null | head -10 >> "$REPORT_FILE" || true
else
    grep -r "export default function\|export default class\|export const.*=.*(" $SRC_DIRS --include="*.tsx" --include="*.ts" -l 2>/dev/null | head -10 >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Data fetching
echo "### Data Fetching Pattern" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if command -v rg &>/dev/null; then
    rg "use client|use server|useSWR|useQuery|getServerSideProps|server action" $SRC_DIRS -l 2>/dev/null | head -10 >> "$REPORT_FILE" || true
else
    grep -r "use client\|use server\|useSWR\|useQuery\|getServerSideProps" $SRC_DIRS --include="*.tsx" --include="*.ts" -l 2>/dev/null | head -10 >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# State management
echo "### State Management Pattern" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if command -v rg &>/dev/null; then
    rg "zustand|redux|jotai|valtio|recoil|nanostores" $SRC_DIRS -l 2>/dev/null | head -5 >> "$REPORT_FILE" || echo "  → ไม่พบ global state library (อาจใช้ useState/Context)" >> "$REPORT_FILE"
else
    grep -r "zustand\|redux\|jotai\|nanostores" $SRC_DIRS --include="*.ts" --include="*.tsx" -l 2>/dev/null | head -5 >> "$REPORT_FILE" || echo "  → ไม่พบ" >> "$REPORT_FILE"
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 4: Duplicate & Problem Detection
# ───────────────────────────────────────────
echo "▶ [4/6] Detecting duplicates and anti-patterns..."
cat >> "$REPORT_FILE" << 'EOF'
## 4. ปัญหาและโค้ดซ้ำที่พบ

EOF

# Duplicate fetch/http calls
echo "### Duplicate HTTP/Fetch Logic" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if command -v rg &>/dev/null; then
    rg "fetch\(|axios\.|\.get\(|\.post\(" $SRC_DIRS -l 2>/dev/null | head -20 >> "$REPORT_FILE" || true
else
    grep -r "fetch(\|axios\.\|\.get(\|\.post(" $SRC_DIRS --include="*.ts" --include="*.tsx" -l 2>/dev/null | head -20 >> "$REPORT_FILE" || true
fi
FETCH_COUNT=$(cat "$REPORT_FILE" | grep -c "fetch\|axios" 2>/dev/null || echo 0)
echo "" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Hardcoded values
echo "### Hardcoded Values (ควรเป็น env var)" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if command -v rg &>/dev/null; then
    rg "localhost:[0-9]+|http://[^'\"]|https://[a-z]+\.[a-z]+" $SRC_DIRS --type ts --type tsx 2>/dev/null | grep -v "test\|spec\|\.env\|config\|comment\|//" | head -15 >> "$REPORT_FILE" || true
else
    grep -rn "localhost:\|http://\|https://" $SRC_DIRS --include="*.ts" --include="*.tsx" 2>/dev/null | grep -v "test\|spec\|\.env" | head -15 >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# God files (files > 200 lines)
echo "### ไฟล์ขนาดใหญ่ (>200 บรรทัด) — อาจเป็น God Component" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
find $SRC_DIRS -name "*.tsx" -o -name "*.ts" -o -name "*.py" -o -name "*.rs" 2>/dev/null \
    | grep -v node_modules | grep -v ".d.ts" \
    | xargs wc -l 2>/dev/null \
    | sort -rn \
    | awk '$1 > 200' \
    | head -15 >> "$REPORT_FILE" || true
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Debt markers
echo "### Technical Debt Markers" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if command -v rg &>/dev/null; then
    rg "TODO|FIXME|HACK|XXX|@ts-ignore|@ts-nocheck|eslint-disable" $SRC_DIRS 2>/dev/null | head -20 >> "$REPORT_FILE" || true
else
    grep -rn "TODO\|FIXME\|HACK\|XXX\|@ts-ignore\|@ts-nocheck" $SRC_DIRS --include="*.ts" --include="*.tsx" 2>/dev/null | head -20 >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Deep relative imports (circular indicators)
echo "### Deep Relative Imports (อาจมี circular dependency)" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if command -v rg &>/dev/null; then
    rg "from ['\"]\.\.\/\.\.\/\.\." $SRC_DIRS 2>/dev/null | head -10 >> "$REPORT_FILE" || echo "  → ไม่พบ deep relative imports" >> "$REPORT_FILE"
else
    grep -rn "from.*\.\./\.\./\.\." $SRC_DIRS --include="*.ts" --include="*.tsx" 2>/dev/null | head -10 >> "$REPORT_FILE" || echo "  → ไม่พบ" >> "$REPORT_FILE"
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 5: Git Intelligence
# ───────────────────────────────────────────
echo "▶ [5/6] Git analysis..."
cat >> "$REPORT_FILE" << 'EOF'
## 5. Git Intelligence

EOF

if [ "$HAS_GIT" = "1" ] && git rev-parse --is-inside-work-tree &>/dev/null; then
    echo "### Most Changed Files (hotspots)" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    git log --oneline --name-only --diff-filter=M 2>/dev/null \
        | grep -E "\.(ts|tsx|py|rs|go)$" \
        | sort | uniq -c | sort -rn | head -10 >> "$REPORT_FILE" || true
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    echo "### Recent Changes (7 days)" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    git log --oneline --since="7 days ago" 2>/dev/null | head -15 >> "$REPORT_FILE" || echo "ไม่มี commit ใน 7 วัน" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
else
    echo "_ไม่ใช่ git repo หรือไม่มี git_" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# ───────────────────────────────────────────
# SECTION 6: Existing Docs
# ───────────────────────────────────────────
echo "▶ [6/6] Checking existing documentation..."
cat >> "$REPORT_FILE" << 'EOF'
## 6. เอกสารที่มีอยู่

EOF

for DOC in CLAUDE.md AGENTS.md README.md .cursorrules .github/copilot-instructions.md; do
    if [ -f "$DOC" ]; then
        echo "### $DOC (50 บรรทัดแรก)" >> "$REPORT_FILE"
        echo '```' >> "$REPORT_FILE"
        head -50 "$DOC" >> "$REPORT_FILE"
        echo '```' >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    fi
done

# ───────────────────────────────────────────
# SUMMARY
# ───────────────────────────────────────────
cat >> "$REPORT_FILE" << 'EOF'
---

## 📋 สรุปสำหรับ Phase 2 Discovery Report

> AI ควรอ่านทุก section ด้านบน แล้วสรุปในรูปแบบ Phase 2 ของ SKILL.md
> รวมถึงระบุ: Tech Stack จริง, Pattern ที่ใช้, ปัญหาที่พบ, และคำถามที่ต้องการคำตอบจากผู้ใช้

EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Deep Scan เสร็จสิ้น → $REPORT_FILE"
echo "   ขนาดรายงาน: $(wc -l < "$REPORT_FILE") บรรทัด"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
