#!/bin/bash
# backup.sh — สร้าง backup/snapshot ก่อนทำการแก้ไขโค้ดใดๆ
# รันก่อนเสมอเมื่อ god-architecture จะทำการแก้ไขโปรเจกต์
#
# Usage:
#   bash scripts/backup.sh [label]
#   bash scripts/backup.sh "before-auth-refactor"
#
# Output:
#   - git stash (ถ้ามี uncommitted changes)
#   - git tag snapshot
#   - backup dir (ถ้าไม่ใช่ git repo)
#   - ROLLBACK.md พร้อมคำสั่ง rollback

set -euo pipefail

LABEL="${1:-god-arch-$(date '+%Y%m%d-%H%M%S')}"
BACKUP_DIR=".god-arch-backups"
ROLLBACK_FILE="ROLLBACK.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
HAS_GIT=$(git rev-parse --is-inside-work-tree 2>/dev/null && echo "yes" || echo "no")

echo "╔══════════════════════════════════════════╗"
echo "║  🛡️  god-architecture — Backup & Snapshot ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "Label: $LABEL"
echo "Time : $TIMESTAMP"
echo ""

# ───────────────────────────────────────────
# MODE A: Git repo → ใช้ git
# ───────────────────────────────────────────
if [ "$HAS_GIT" = "yes" ]; then
    echo "▶ Git repo detected — ใช้ git snapshot"
    echo ""

    # Check working tree status
    DIRTY=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "HEAD")
    CURRENT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
    SHORT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

    echo "  Branch : $CURRENT_BRANCH"
    echo "  Commit : $SHORT_COMMIT"
    echo "  Dirty  : $DIRTY files uncommitted"
    echo ""

    # Step 1: Stash uncommitted changes (ถ้ามี)
    STASH_REF=""
    if [ "$DIRTY" -gt 0 ]; then
        echo "  📦 Stashing $DIRTY uncommitted files..."
        git add -A
        STASH_MSG="god-arch-backup: $LABEL"
        git stash push -m "$STASH_MSG" 2>/dev/null
        STASH_REF=$(git stash list | grep "$STASH_MSG" | head -1 | cut -d: -f1)
        echo "  ✅ Stash created: $STASH_REF"
    else
        echo "  ℹ️  Working tree clean — ไม่ต้อง stash"
    fi

    # Step 2: Create snapshot tag
    TAG_NAME="god-arch/$LABEL"
    git tag "$TAG_NAME" 2>/dev/null && echo "  ✅ Tag created: $TAG_NAME" || echo "  ⚠️  Tag '$TAG_NAME' มีอยู่แล้ว — ข้ามการสร้าง tag"

    # Step 3: Write ROLLBACK.md
    cat > "$ROLLBACK_FILE" << ROLLBACK
# 🔄 Rollback Guide

Generated by god-architecture backup.sh
Backup label : **$LABEL**
Timestamp    : $TIMESTAMP
Branch       : $CURRENT_BRANCH
Commit       : $CURRENT_COMMIT ($SHORT_COMMIT)
Stash        : ${STASH_REF:-"(ไม่มี — working tree สะอาด)"}

---

## วิธี Rollback

### Option 1: Hard Reset (ย้อนกลับทุกอย่าง รวม uncommitted)
\`\`\`bash
# ⚠️ ลบการเปลี่ยนแปลงทั้งหมดหลัง commit นี้
git reset --hard $CURRENT_COMMIT
git clean -fd
\`\`\`

### Option 2: Revert จาก Tag (ปลอดภัยกว่า)
\`\`\`bash
# ดู snapshot ที่บันทึกไว้
git show $TAG_NAME --stat

# สร้าง branch ใหม่จาก snapshot
git checkout -b rollback/$LABEL $TAG_NAME
\`\`\`

### Option 3: Restore Stash (ถ้า stash ถูกสร้าง)
\`\`\`bash
# ดู stash list
git stash list

# Restore
git stash pop ${STASH_REF:-"stash@{0}"}
\`\`\`

### Option 4: Cherry-pick เฉพาะไฟล์
\`\`\`bash
# ดึงเฉพาะไฟล์จาก snapshot
git checkout $TAG_NAME -- path/to/specific/file.ts
\`\`\`

---

## ดู diff ว่าเปลี่ยนอะไรไป
\`\`\`bash
git diff $SHORT_COMMIT HEAD
git diff $SHORT_COMMIT HEAD --stat
\`\`\`
ROLLBACK

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ Backup เสร็จสิ้น"
    echo "   Tag      : $TAG_NAME"
    echo "   Rollback : $ROLLBACK_FILE"
    echo ""
    echo "💡 ถ้าต้องการ rollback:"
    echo "   git reset --hard $SHORT_COMMIT   (hard — ลบทุกอย่าง)"
    echo "   git checkout -b fix $TAG_NAME    (safe — สร้าง branch ใหม่)"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ───────────────────────────────────────────
# MODE B: ไม่ใช่ git repo → copy ไฟล์
# ───────────────────────────────────────────
else
    echo "▶ ไม่ใช่ git repo — ใช้ directory backup"
    echo ""

    mkdir -p "$BACKUP_DIR/$LABEL"
    SNAPSHOT_DIR="$BACKUP_DIR/$LABEL"

    # Copy ทุกอย่างยกเว้น node_modules, dist, .next
    rsync -a \
        --exclude="node_modules" \
        --exclude=".next" \
        --exclude="dist" \
        --exclude="build" \
        --exclude="__pycache__" \
        --exclude=".god-arch-backups" \
        . "$SNAPSHOT_DIR/" 2>/dev/null || \
    cp -r . "$SNAPSHOT_DIR/" 2>/dev/null

    SNAPSHOT_SIZE=$(du -sh "$SNAPSHOT_DIR" 2>/dev/null | cut -f1)

    cat > "$ROLLBACK_FILE" << ROLLBACK
# 🔄 Rollback Guide

Generated by god-architecture backup.sh
Backup label : **$LABEL**
Timestamp    : $TIMESTAMP
Snapshot dir : $SNAPSHOT_DIR ($SNAPSHOT_SIZE)

---

## วิธี Rollback

### Restore ทั้งหมด
\`\`\`bash
# ⚠️ จะ overwrite ไฟล์ปัจจุบัน
cp -r $SNAPSHOT_DIR/. .
\`\`\`

### Restore เฉพาะไฟล์
\`\`\`bash
cp $SNAPSHOT_DIR/src/components/MyComponent.tsx src/components/MyComponent.tsx
\`\`\`

### ดู diff
\`\`\`bash
diff -r $SNAPSHOT_DIR/src ./src
\`\`\`
ROLLBACK

    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ Backup เสร็จสิ้น"
    echo "   Snapshot : $SNAPSHOT_DIR ($SNAPSHOT_SIZE)"
    echo "   Rollback : $ROLLBACK_FILE"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
fi
