#!/bin/bash
# find-duplicates.sh — ตรวจหา duplicate code, dead code, unused exports
#
# Tools ที่ใช้ (ติดตั้งอัตโนมัติถ้าไม่มี):
#   jscpd      — Copy-Paste Detection (duplicate code blocks)
#   ts-prune   — Unused TypeScript exports
#   unimported — Files ที่ไม่มีใครนำเข้า
#   rg         — ค้นหา dead code patterns
#
# Usage:
#   bash scripts/find-duplicates.sh [src_dir]
#   bash scripts/find-duplicates.sh src/

set -euo pipefail

SRC_DIR="${1:-src}"
REPORT_FILE="god-arch-duplicates-report.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
IS_TS=$([ -f "tsconfig.json" ] && echo "yes" || echo "no")
IS_NODE=$([ -f "package.json" ] && echo "yes" || echo "no")
HAS_RG=$(command -v rg &>/dev/null && echo "yes" || echo "no")

if [ ! -d "$SRC_DIR" ]; then
    echo "❌ Source directory not found: $SRC_DIR"
    exit 1
fi

echo "╔══════════════════════════════════════════╗"
echo "║  🔬 god-architecture — Duplicate Finder  ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "Scanning: $SRC_DIR"
echo "Report  : $REPORT_FILE"
echo ""

cat > "$REPORT_FILE" << HEADER
# 🔬 Duplicate & Dead Code Report

> Auto-generated by \`scripts/find-duplicates.sh\`
> Timestamp: $TIMESTAMP
> Source: $SRC_DIR

---

HEADER

# ───────────────────────────────────────────
# SECTION 1: jscpd — Copy-Paste Detection
# ───────────────────────────────────────────
echo "▶ [1/5] Running jscpd (Copy-Paste Detection)..."
cat >> "$REPORT_FILE" << 'EOF'
## 1. Copy-Paste Duplication (jscpd)

> ตรวจหา code block ที่ copy มาจากกัน (≥ 5 บรรทัด, ≥ 50 tokens)

EOF

if [ "$IS_NODE" = "yes" ]; then
    if ! command -v jscpd &>/dev/null && ! npx --yes jscpd --version &>/dev/null 2>&1; then
        echo "  ⚠️  jscpd ไม่พบ — ใช้ npx"
    fi

    mkdir -p .jscpd-report
    npx --yes jscpd "$SRC_DIR" \
        --min-lines 5 \
        --min-tokens 50 \
        --reporters "console,json" \
        --output ".jscpd-report" \
        --ignore "**/*.test.*,**/*.spec.*,**/*.d.ts" \
        2>/dev/null >> "$REPORT_FILE" || \
    echo "_jscpd ไม่สามารถรันได้ในสภาพแวดล้อมนี้_" >> "$REPORT_FILE"

    # Parse JSON report ถ้ามี
    if [ -f ".jscpd-report/jscpd-report.json" ] && command -v jq &>/dev/null; then
        echo "" >> "$REPORT_FILE"
        echo "### Summary (จาก jscpd JSON)" >> "$REPORT_FILE"
        echo '```' >> "$REPORT_FILE"
        jq '{total_duplicates: .statistics.total.duplicatedLines, percentage: .statistics.total.percentage, files_with_duplication: (.duplicates | length)}' \
            .jscpd-report/jscpd-report.json 2>/dev/null >> "$REPORT_FILE" || true
        echo '```' >> "$REPORT_FILE"
    fi
else
    echo "_ไม่ใช่ Node project — ข้าม jscpd_" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 2: ts-prune — Unused Exports
# ───────────────────────────────────────────
echo "▶ [2/5] Running ts-prune (Unused Exports)..."
cat >> "$REPORT_FILE" << 'EOF'
## 2. Unused TypeScript Exports (ts-prune)

> exports ที่ไม่มีไฟล์ไหน import ไปใช้เลย — safe to delete

EOF

if [ "$IS_TS" = "yes" ] && [ "$IS_NODE" = "yes" ]; then
    echo '```' >> "$REPORT_FILE"
    npx --yes ts-prune 2>/dev/null | { grep -v "used in module" || true; } | head -50 >> "$REPORT_FILE" || \
    echo "_ts-prune ไม่สามารถรันได้ — ตรวจสอบ tsconfig.json_" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
else
    echo "_ไม่ใช่ TypeScript project — ข้าม ts-prune_" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 3: unimported — Orphan Files
# ───────────────────────────────────────────
echo "▶ [3/5] Running unimported (Orphan Files)..."
cat >> "$REPORT_FILE" << 'EOF'
## 3. Unimported Files (unimported)

> ไฟล์ที่ไม่มีใคร import เลย — อาจเป็น dead code ที่ลืมลบ

EOF

if [ "$IS_NODE" = "yes" ]; then
    echo '```' >> "$REPORT_FILE"
    npx --yes unimported 2>/dev/null | head -50 >> "$REPORT_FILE" || \
    echo "_unimported ไม่สามารถรันได้ในสภาพแวดล้อมนี้_" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
else
    echo "_ไม่ใช่ Node project — ข้าม unimported_" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 4: rg — Duplicate Pattern Detection
# ───────────────────────────────────────────
echo "▶ [4/5] Pattern-based duplicate detection (rg/grep)..."
cat >> "$REPORT_FILE" << 'EOF'
## 4. Duplicate Logic Patterns (rg scan)

> ตรวจหา pattern ที่ทำงานซ้ำกัน เช่น fetch logic, error handling, validation

EOF

# 4.1 Duplicate fetch/http
echo "### 4.1 ไฟล์ที่มี HTTP/Fetch logic (อาจซ้ำกัน)" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if [ "$HAS_RG" = "yes" ]; then
    rg "fetch\(|axios\.|\.get\(|\.post\(|\.put\(|\.delete\(" "$SRC_DIR" -l 2>/dev/null \
        | sort | uniq >> "$REPORT_FILE" || true
else
    grep -r "fetch(\|axios\.\|\.get(\|\.post(" "$SRC_DIR" --include="*.ts" --include="*.tsx" -l 2>/dev/null \
        | sort | uniq >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 4.2 Duplicate function signatures
echo "### 4.2 Function names ที่ซ้ำกันข้ามไฟล์" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if [ "$HAS_RG" = "yes" ]; then
    rg "^(export )?(async )?function [a-zA-Z]+" "$SRC_DIR" -o 2>/dev/null \
        | sed 's/.*function //' \
        | sort | uniq -d | head -20 >> "$REPORT_FILE" || true
else
    grep -rn "^export.*function\|^async function\|^function" "$SRC_DIR" \
        --include="*.ts" --include="*.tsx" -h 2>/dev/null \
        | sed 's/.*function //' | sed 's/(.*//' \
        | sort | uniq -d | head -20 >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 4.3 Duplicate interface/type names
echo "### 4.3 Type/Interface names ที่ซ้ำกัน" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if [ "$HAS_RG" = "yes" ]; then
    rg "^(export )?(interface|type) [A-Z][a-zA-Z]+" "$SRC_DIR" -o 2>/dev/null \
        | sed 's/.*\(interface\|type\) //' \
        | sort | uniq -d | head -20 >> "$REPORT_FILE" || true
else
    grep -rn "^export interface\|^export type\|^interface\|^type " "$SRC_DIR" \
        --include="*.ts" --include="*.tsx" -h 2>/dev/null \
        | sed 's/.*\(interface\|type\) //' | sed 's/ .*//' \
        | sort | uniq -d | head -20 >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# 4.4 Hardcoded strings ที่ซ้ำกัน
echo "### 4.4 String literals ที่ซ้ำกันหลายที่ (ควรเป็น constant)" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
if [ "$HAS_RG" = "yes" ]; then
    rg "'[a-zA-Z/-]{4,}'|\"[a-zA-Z/-]{4,}\"" "$SRC_DIR" -o 2>/dev/null \
        | sort | uniq -c | sort -rn \
        | awk '$1 >= 3' | head -20 >> "$REPORT_FILE" || true
else
    grep -roh "'[a-zA-Z/-]\{4,\}'\|\"[a-zA-Z/-]\{4,\}\"" "$SRC_DIR" \
        --include="*.ts" --include="*.tsx" 2>/dev/null \
        | sort | uniq -c | sort -rn | awk '$1 >= 3' | head -20 >> "$REPORT_FILE" || true
fi
echo '```' >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 5: Summary & Action Plan
# ───────────────────────────────────────────
echo "▶ [5/5] Generating summary..."
cat >> "$REPORT_FILE" << 'EOF'
## 5. แผนการแก้ไข (สำหรับ AI อ่านและสรุปต่อ)

> อ่าน sections 1-4 แล้วสรุปในรูปนี้:

| # | ปัญหา | ไฟล์ที่เกี่ยวข้อง | Priority | แนวทางแก้ |
|---|-------|-----------------|----------|----------|
| 1 | (duplicate fetch) | ... | 🔴 High | สร้าง shared api client |
| 2 | (unused export) | ... | 🟡 Med | ลบ หรือ เพิ่ม export ใน index |
| 3 | (orphan file) | ... | 🟢 Low | ตรวจสอบแล้วลบถ้าไม่ใช้ |

### Tools เพิ่มเติม (ถ้าต้องการ deep analysis)

```bash
# Madge — visualize circular dependencies
npx madge --circular src/

# depcheck — unused npm dependencies
npx depcheck

# ESLint no-unused-vars (ถ้า setup ESLint แล้ว)
npx eslint src/ --rule '{"no-unused-vars": "error"}' --ext .ts,.tsx

# Python: vulture — dead code detection
pip install vulture && vulture src/ --min-confidence 80
```
EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Duplicate scan เสร็จสิ้น → $REPORT_FILE"
echo "   ขนาดรายงาน: $(wc -l < "$REPORT_FILE") บรรทัด"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
