#!/bin/bash
# mcp-detect.sh — ตรวจ MCP tools ที่ผู้ใช้ติดตั้งไว้
# Output: รายการ MCP servers + แนะนำ tools ที่เหมาะกับโปรเจกต์นี้

set -uo pipefail
PROJECT_PATH="$(cd "${1:-.}" && pwd)"
REPORT_FILE="$PROJECT_PATH/god-arch-mcp-report.md"

echo "╔══════════════════════════════════════════╗"
echo "║  🔌 god-architecture — MCP Detector      ║"
echo "╚══════════════════════════════════════════╝"
echo ""

INSTALLED=()
MISSING_RECOMMENDED=()

cat > "$REPORT_FILE" << 'HEADER'
# 🔌 MCP Tools Report

> Auto-generated by `scripts/mcp-detect.sh`

HEADER

echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 1: ตรวจ MCP config files
# ───────────────────────────────────────────
echo "▶ [1/3] Scanning MCP configuration files..."
cat >> "$REPORT_FILE" << 'EOF'
## 1. MCP Config Files Found

EOF

MCP_FOUND=0

# Claude Code — project level
for f in ".mcp.json" ".claude/mcp.json" ".claude/settings.json"; do
    if [ -f "$PROJECT_PATH/$f" ]; then
        echo "  ✅ Found: $f"
        echo "### $f" >> "$REPORT_FILE"
        echo '```json' >> "$REPORT_FILE"
        cat "$PROJECT_PATH/$f" >> "$REPORT_FILE" 2>/dev/null | head -50
        echo '```' >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        MCP_FOUND=$((MCP_FOUND + 1))
    fi
done

# Claude Code — user level
for f in "$HOME/.claude/settings.json" "$HOME/.claude/mcp.json"; do
    if [ -f "$f" ]; then
        echo "  ✅ Found (user-level): $f"
        echo "### $(basename $f) (user-level)" >> "$REPORT_FILE"
        echo '```json' >> "$REPORT_FILE"
        python3 -c "
import json
with open('$f') as fh:
    d = json.load(fh)
    servers = d.get('mcpServers', {})
    print(json.dumps({'mcpServers': {k: {'command': v.get('command','?')} for k,v in servers.items()}}, indent=2))
" 2>/dev/null >> "$REPORT_FILE" || head -30 "$f" >> "$REPORT_FILE"
        echo '```' >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        MCP_FOUND=$((MCP_FOUND + 1))
    fi
done

# Gemini CLI
for f in "$HOME/.gemini/config.json" "$HOME/.gemini/settings.json"; do
    if [ -f "$f" ]; then
        echo "  ✅ Found (Gemini): $f"
        echo "### Gemini Config" >> "$REPORT_FILE"
        echo '```json' >> "$REPORT_FILE"
        echo '{"notice":"Gemini config detected (content redacted for security)"}' >> "$REPORT_FILE"
        echo '```' >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        MCP_FOUND=$((MCP_FOUND + 1))
    fi
done

# Codex CLI
for f in "$HOME/.codex/config.json"; do
    if [ -f "$f" ]; then
        echo "  ✅ Found (Codex): $f"
        MCP_FOUND=$((MCP_FOUND + 1))
    fi
done

if [ $MCP_FOUND -eq 0 ]; then
    echo "  ⚠️  ไม่พบ MCP config files"
    echo "_ไม่พบ MCP configuration files ใดๆ_" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# ───────────────────────────────────────────
# SECTION 2: Parse installed MCP servers
# ───────────────────────────────────────────
echo ""
echo "▶ [2/3] Parsing installed MCP servers..."
cat >> "$REPORT_FILE" << 'EOF'
## 2. MCP Servers Detected

EOF

# Extract server names from all config files
ALL_SERVERS=""
for f in "$PROJECT_PATH/.mcp.json" "$PROJECT_PATH/.claude/settings.json" \
         "$HOME/.claude/settings.json" "$HOME/.claude/mcp.json"; do
    if [ -f "$f" ]; then
        SERVERS=$(python3 -c "
import json, sys
try:
    with open('$f') as fh:
        d = json.load(fh)
    servers = d.get('mcpServers', d.get('mcp_servers', {}))
    for name, cfg in servers.items():
        cmd = cfg.get('command','') + ' ' + ' '.join(cfg.get('args',[]))
        print(f'{name}|{cmd.strip()}')
except: pass
" 2>/dev/null || true)
        ALL_SERVERS="$ALL_SERVERS
$SERVERS"
    fi
done

if [ -n "$(echo "$ALL_SERVERS" | tr -d '\n ')" ]; then
    echo '```' >> "$REPORT_FILE"
    echo "$ALL_SERVERS" | grep -v "^$" | sort | uniq | while IFS='|' read -r name cmd; do
        [ -n "$name" ] && echo "✅ $name — $cmd"
        [ -n "$name" ] && INSTALLED+=("$name")
    done | tee -a "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
else
    echo "  ⚠️  ไม่พบ MCP servers ที่ติดตั้ง"
    echo "_ไม่พบ MCP servers_" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# ───────────────────────────────────────────
# SECTION 3: แนะนำ MCP ที่เหมาะกับโปรเจกต์นี้
# ───────────────────────────────────────────
echo ""
echo "▶ [3/3] Recommending MCP tools for this project..."
cat >> "$REPORT_FILE" << 'EOF'
## 3. MCP Tools Recommended for This Project

EOF

# ตรวจ project type แล้วแนะนำ
echo "### แนะนำตาม Project Type" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# GitHub MCP
if [ -d ".git" ] || [ -f ".github" ]; then
    echo "  💡 **GitHub MCP** — repo มี git"
    cat >> "$REPORT_FILE" << 'EOF'
#### GitHub MCP (แนะนำ — พบ .git)
```json
"github": {
  "command": "npx", "args": ["-y", "@modelcontextprotocol/server-github"],
  "env": { "GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_TOKEN}" }
}
```
EOF
fi

# Filesystem MCP (เกือบทุกโปรเจกต์)
echo "  💡 **Filesystem MCP** — ช่วยอ่าน/เขียนไฟล์"
cat >> "$REPORT_FILE" << 'EOF'
#### Filesystem MCP (แนะนำทุกโปรเจกต์)
```json
"filesystem": {
  "command": "npx",
  "args": ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/project"]
}
```
EOF

# Supabase (ถ้ามี supabase)
if grep -r "supabase" "$PROJECT_PATH/package.json" 2>/dev/null | grep -q "supabase"; then
    echo "  💡 **Supabase MCP** — พบ supabase dependency"
    cat >> "$REPORT_FILE" << 'EOF'
#### Supabase MCP (แนะนำ — พบ supabase)
```json
"supabase": {
  "command": "npx", "args": ["-y", "@supabase/mcp-server-supabase@latest",
    "--supabase-url", "${SUPABASE_URL}", "--supabase-key", "${SUPABASE_SERVICE_KEY}"]
}
```
EOF
fi

# Playwright MCP (ถ้ามี)
if grep -r "playwright" "$PROJECT_PATH/package.json" 2>/dev/null | grep -q "playwright"; then
    echo "  💡 **Playwright MCP** — พบ playwright"
    cat >> "$REPORT_FILE" << 'EOF'
#### Playwright MCP (แนะนำ — พบ playwright)
```json
"playwright": {
  "command": "npx", "args": ["-y", "@playwright/mcp@latest"]
}
```
EOF
fi

echo "" >> "$REPORT_FILE"
echo "### ติดตั้ง MCP ใน Claude Code" >> "$REPORT_FILE"
cat >> "$REPORT_FILE" << 'EOF'
```bash
# เพิ่ม MCP server ผ่าน CLI
claude mcp add <name> <command> [args...]

# ตัวอย่าง
claude mcp add filesystem npx -y @modelcontextprotocol/server-filesystem /project
claude mcp add github npx -y @modelcontextprotocol/server-github

# ดู MCP ที่ติดตั้งอยู่
claude mcp list
```
EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ MCP Detection เสร็จสิ้น → $REPORT_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
